import type { Metadata } from 'next';
import {HeroUIProvider} from "@heroui/react";
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/utils/store';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

// TODO: Rename title & description when figure out name of app. 🤔
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroUIProvider>
        <StoreProvider>{children}</StoreProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}

// 2-3-25 TODO: Create one main Provider component that renders all the components.
